### PR TITLE
Added functionalty to deploy multiple meteor apps with a shared reverse proxy

### PR DESCRIPTION
**Pull request by shaiamir**

### CODE REVIEW

**Comment by zodern** [comment]
Thank you for working on this! I should have time to look at it early next week.

**Comment by zodern** [comment]
Tomorrow I will try using the reverse proxy.

Here are some thoughts:
- We currently have a proxy module that basically does nothing. I think you should use that instead of adding the `nginx` module.
- You could move the list of domains from `meteor.nginx.domains` to `proxy.domains` and `nginx` to `proxy.sharedConfig` (there probably is a better name than sharedConfig). That way all of the configuration for the reverse proxy are in one place and it is obvious when the reverse proxy is being used.
- When would the config options `meteor.nginx.name`, `nginx.name`, and `mongo.dbDir` need to be changed?
- `mup setup` should setup, upload the env variables, and start the shared proxy if needed.
- ~~We have the `mup reconfig` for the app. I think we should reuse the naming and have `mup nginx reconfig` instead of `mup nginx envconfig`~~ Edit: `mup reconfig` is just an alias for `mup meteor envconfig`. `mup nginx envconfig` is fine.

I am very excited about this feature, and you did a great job implementing it!

**Comment by shadowcodex** [comment]
@shaiamir can you fix your conflicts in this?

@zodern it is my understanding that we are going to prioritize this PR and then modify my PR https://github.com/zodern/meteor-up/pull/496 to address the changes. Is that correct?

**Comment by zodern** [comment]
yes

**Comment by shaiamir** [comment]
@shadowcodex Can you please explain what you want me to do? On which branch (what should I clone, commit to where?)

@zodern Do you want me to do code changes along the lines of the "thoughts" you mentioned above?

**Comment by zodern** [comment]
> Do you want me to do code changes along the lines of the "thoughts" you mentioned above?

If you have time in the next couple days, that would be great!

> it is my understanding that we are going to prioritize this PR and then modify my PR #496 to address the changes. Is that correct?

I should have given more than a one word answer. By changes are you referring to what we discussed in #496 or also to my "thoughts" I wrote here? If it is the former, yes.

**Comment by shadowcodex** [comment]
@zodern Yes you are correct, I was talking about what we discussed in https://github.com/zodern/meteor-up/pull/496. 

@shaiamir as far as conflicts go, we may have to resolve them once we merge the PR in.

**Comment by zodern** [comment]
Thanks @shaiamir.

**Pull request merged**
