### PR TITLE
Add some missing babel packages

### PR DESCRIPTION
**Pull request by MichaelJCole**
Hey, found a couple missing packages while trying to install the new mup.

### CODE REVIEW

**Comment by madushan1000** [comment]
These packages should be automatically resolved using `.babelrc` file. Are you using npm2?

**Comment by MichaelJCole** [comment]
Hey Mudashan, no, I'm using what meteor uses - 0.10.43

**Comment by madushan1000** [comment]
What is the npm version? `npm install` properly install all the packages if you are using npm version 3.

**Comment by MichaelJCole** [comment]
Hey Madushan, Meteor doesn't use npm 3.  It uses the version with node
0.10.43.  That's why these packages should be included until [Meteor starts
using a newer version of node](https://github.com/meteor/meteor/issues/5124)

On Mon, May 30, 2016 at 11:35 PM, Madushan Nishantha <
notifications@github.com> wrote:

> What is the npm version? npm install properly install all the packages if
> you are using npm version 3.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/kadirahq/meteor-up/pull/131#issuecomment-222590582,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABb2FqxLXIpDO9wvsX-B_Y3RKGF8tgGnks5qG7p2gaJpZM4IpV0L
> .

## 

Michael Cole
Founder and Engineer
https://bigSmall.io

**Comment by madushan1000** [comment]
Meteor up doesn't necessarily has to use meteor node/npm version.

**Comment by MichaelJCole** [comment]
That is true, but why make it harder for the next person :-)  

TBH, I gave up on the new mup and [forked](https://github.com/MichaelJCole/meteor-up) the old one because this makes it seem like few people are using the new version.

If you don't want to add these packages, maybe mentioning it in the readme?

**Comment by madushan1000** [comment]
Yeah, I'll update the readme to mention that meteor-up requires npm3. But It wouldn't bother the end user because we are going to publish the transpiled code at npm.

**Pull request closed without merging**
