### PR TITLE
Different env for different servers

### PR DESCRIPTION
**Pull request by artpolikarpov**
I itterate sessions first, then build `env`, then run taskList

### CODE REVIEW

**Comment by artpolikarpov** [comment]
This one try to solve #244. It’s not an ideal solution, because now we have to run as many task lists as servers we have. But it brings one important and essential feature back. Now you can have override global `env` with custom one:

```
module.exports = {
    // Server authentication info
    "servers": {
        '1': {
            "host": "104.197.203.70",
            "username": "artpolikarpov",
            "pem": "/Users/artpolikarpov/Projects/Chatra/DEPLOY/google_compute_engine",
            "env": {
                // custom env!
                "LABEL": "104-197-203-70",
                "CDN": "https://1177857738.somecdn.io"
            }
        },
  ...
```

**Comment by etyp** [comment]
+1

**Comment by elie222** [comment]
+100

**Comment by elie222** [comment]
@madushan1000 I see PRs are being accepted, but this one hasn't been, nor does it have a comment. Can we get an update?

**Comment by madushan1000** [comment]
This patch requires some integration testing. If someone can write some, I can run the tests and merge. Otherwise, it'll take some more time.

**Comment by idanwe** [comment]
@artpolikarpov Do you have any updates on this or you were able to find other solution?

**Comment by elie222** [comment]
What we do is use different mup folders for different servers. Slightly
annoying, but works fine.

Elie

**Comment by artpolikarpov** [comment]
@idanwe, no updates here. I just forked this repo and monkey-patched it.

**Comment by stevenhornung** [comment]
@artpolikarpov Yeah, I did the same. Still wasn't super happy with the solution given that I was trying to use an outdated meteor-cluster package in parallel with this package (which has had its share of ups and downs). I ended up scrapping it all and moving my deployment over to AWS Elastic Beanstalk and man, what a drastic improvement to deployment and scalability! Will never go back :D

**Comment by elie222** [comment]
What set up did you use elastic beanstalk? Does it autoscale?

On 5 Jun 2017 19:59, "Steven Hornung" <notifications@github.com> wrote:

@artpolikarpov <https://github.com/artpolikarpov> Yeah, I did the same.
Still wasn't super happy with the solution given that I was trying to use
an outdated meteor-cluster package in parallel with this package (which has
had its share of ups and downs). I ended up scrapping it all and moving my
deployment over to AWS Elastic Beanstalk and man, what a drastic
improvement to deployment and scalability! Will never go back :D

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/zodern/meteor-up/pull/248#issuecomment-306243302>, or mute
the thread

**Comment by vbelolapotkov** [comment]
@stevenhornung could you share your experience with elastic beanstalk? any guides or useful link on how set it up?

**Comment by zodern** [comment]
This will be available in 1.3. To avoid having multiple task lists, it registers an improved `copy` task with nodemiral which supports host specific variables. It is configured in `meteor.servers.<server name>.env` instead.

Thanks for your work on this @artpolikarpov.

**Pull request closed without merging**
