### PR TITLE
fix reverting to previous working version

### PR DESCRIPTION
**Pull request by sirpy**
the mv command simply moves the last directory into the current directory instead of renaming it.
we need to first rename current into "buggy" and then last into current.
perhaps we should also remove any old "buggy" directory

### CODE REVIEW

**Comment by shadowcodex** [comment]
What is the purpose of retaining the buggy build? 
If you are just trying to clear out current, you could just `rm -rf current` right?

**Comment by sirpy** [comment]
I don't know. I guess you can also delete it. I think I saw that the
original mup saved the buggy version so I just kept the same logic

**Comment by zodern** [comment]
@sirpy, could you please change it to delete the directory instead?

**Comment by zodern** [comment]
Thank you @sirpy

**Pull request merged**
