### PR TITLE
Install additional apt-get packages in docker image if specified

### PR DESCRIPTION
**Pull request by ckiely91**
Added additional option to mup.js to specify an array of apt-get package names. Based on this [gist](https://gist.github.com/so0k/7d4be21c5e2d9abd3743).

This will be a very useful feature to install packages such as graphicsmagick. Let me know if there are ways I can improve this!

### CODE REVIEW

**Comment by madushan1000** [comment]
We already have a proposal to add hooks, https://github.com/kadirahq/meteor-up/pull/65 
Which seems like a more generic feature. @arunoda @mnmtanish what do you think?

**Comment by Ben305** [comment]
This would be very useful to install packages like `graphicsmagick`

+1

**Comment by yubozhao** [comment]
Just wondering the status for the PR, any update?

**Comment by madushan1000** [comment]
The recommended way to add new packages to the docker image is to build one of your own using `meteorhacks/meteord` base image and use that in the deployment.

**Comment by arunoda** [comment]
I hope we allow to change the docker image.
meteord is the base. But you could use any docker image with your own deps.
@madushan1000 I think we need to document it if it's not done.

**Comment by jbg77** [comment]
Yes that I've done and many other people did, two methods:
-by cloning repo, then upload your image on docker hub
-by fork meteord repo, then link you github account to your docker account, and active autobuild

**Comment by zodern** [comment]
@ckiely91 Thanks for working on this. Some base images use a different package manager, such as the alpine image. I would prefer a more general purpose solution where there is an array of commands in the config to run when building the docker image.

**Comment by stefanve** [comment]
I am currently using a manual "post deploy" thing to add my packages:

```
docker exec -it myapp bash
apt install pdftk
```
I have been searching for ways to do it automatically using configuration options in MUP and ended up here. Is there a way to automate that process?

**Comment by zodern** [comment]
@stefanve the best way right now is to create a custom docker image with pdftk already installed.

**Comment by zodern** [comment]
@stefanve an easier way will be available in the next version: #362.

**Pull request closed without merging**
