### PR TITLE
Added the ability to map volumes

### PR DESCRIPTION
**Pull request by marcusrognes**
This is a simple way of adding custom volume mappings in docker.

### CODE REVIEW

**Comment by marcusrognes** [comment]
This lets you map volumes like this:

``` js
module.exports = {
  servers: {
    one: {
      host: '1.2.3.4',
      username: 'root'
      // pem:
      // password:
      // or leave blank for authenticate from ssh-agent
    }
  },

  meteor: {
    name: 'app',
    path: '../app',
    // THIS IS NEW
    volumes: {
        "/host/path": "/container/path",
        "/second/host/path": "/second/container/path"
    },
    servers: {
      one: {}, two: {}, three: {} //list of servers to deploy, from the 'servers' list
    },
    buildOptions: {
      serverOnly: true,
      debug: true,
      mobileSettings: {
        yourMobileSetting: "setting value"
      }
    },
    env: {
      ROOT_URL: 'app.com',
      MONGO_URL: 'mongodb://localhost/meteor'
    },
    logs: { //optional
      driver: 'syslog',
      opts: {
        url:'udp://syslogserverurl.com:1234'
      }
    }
    dockerImage: 'madushan1000/meteord-test', //optional
    deployCheckWaitTime: 60 //default 10
  },

  mongo: { //optional
    oplog: true,
    port: 27017,
    servers: {
      one: {},
    },
  },
};
```

**Comment by eskan** [comment]
+1

**Comment by vjrj** [comment]
+1

**Comment by oli77za** [comment]
+1

**Comment by MasterJames** [comment]
Is there a reason this has not been merged yet?

**Comment by madushan1000** [comment]
@marcusrognes Hi, can you add this information to the README too?

**Comment by marcusrognes** [comment]
@madushan1000 There.

**Comment by madushan1000** [comment]
👍 I'm merging this for now, We can find a better way to handle docker options later.

**Comment by marcusrognes** [comment]
@madushan1000 I do have an implementation for setting docker run variables [here](https://github.com/marcusrognes/meteor-up/commit/bce5d5c64870d20b4211300afdb05ca27c631735)
Altho i feel my implementation is a bit of a quick fix / hack.

**Comment by madushan1000** [comment]
We have discussed a flexible method here https://github.com/kadirahq/meteor-up/issues/75 too..

**Comment by MasterJames** [comment]
Ah thanks for the action and links. I remember that discussion now. It would indeed be better but volumes is pretty fundamental need so good with both maybe.

**Comment by marcusrognes** [comment]
I could create a pull request out of that commit.
@madushan1000 @MasterJames 
Should we continue the discussion on #75 ?

**Comment by MasterJames** [comment]
I'm sure that @madushan1000 would also appreciate that. He's the one to guide you I'm not sure what issues might make it complicated?  Seems pretty straight forward.
I'm thinking a validation check of the values passed would be nice but not critical as its customizable but something like a warning your arguments may need reviewing if missing hypens or argument values etc. would be useful to help people know when somethings wrong.
I bet if you bang out a simple PR he will review and make suggestions. Hopefully you're around if people run in to edge cases that need a tweek or warning adjustment for clarity.

**Pull request merged**
