### PR TITLE
add temporary backup and restore scripts

### PR DESCRIPTION
**Pull request by pravdomil**
fell free to edit PR

### CODE REVIEW

**Comment by zodern** [comment]
Thanks @pravdomil. I think it would be easier to find if it was in the docs, and you could have a link in the roadmap to it.

**Comment by pravdomil** [comment]
@zodern where exactly in docs?

**Comment by zodern** [comment]
Before or after [this section](https://github.com/zodern/meteor-up/blob/master/docs/docs.md#change-mongodb-version) would work.

**Comment by pravdomil** [comment]
done

**Comment by zodern** [comment]
Thanks!

**Pull request merged**
