### PR TITLE
Add `imagePort` to support Docker images not `EXPOSE`-ing port 80

### PR DESCRIPTION
**Pull request by abernix**
Since newer Meteor Docker images are using unprivileged users to run the app (a commonly suggested security move in Node+Docker environments), it is no longer safe to assume that the Docker image will be exposing (nor may it be possible to `EXPOSE`) port 80 depending on the kernel capabilities of the host.

This PR adds an `imagePort` setting in the Docker object (alongside the `image` setting) which defaults to `80` for compatibility with `kadirahq/meteord` (and `meteorhacks/meteord`) but adds the ability to change the *internal* port which is exposed by the docker image (i.e. the port that `--publish PORT:` will map to).

There also a very slight formatting change to the `mup.js.sample` which changes it to actually use the (newer) `docker` object  notation in the `mup.js` created with `mup init`.  This has no bearing on existing configurations but will encourage the use of the new notation.

***

My motive for this PR occurred when I started making [abernix/spaceglue](https://github.com/abernix/spaceglue) in order to stop running Meteor as root which was a necessary change to get around the `--allow-superuser` argument added in Meteor 1.4.2 (well, somewhat unsuccessfully as you might have seen in meteor/meteor#7959).  Since that was fixed, this is less necessary as `abernix/meteord` should be working again.

But I continued to refine `abernix/spaceglue` in the early stages of [this thread](https://forums.meteor.com/t/docker-team-up-to-create-a-reference-docker-image-for-meteor/30829/10).  I think it is ready and it has a lot of important benefits, but more importantly, I think this PR can help open up support for **other** images, like [jshimko/meteor-launchpad](https://github.com/jshimko/meteor-launchpad), [ulexus/meteor](https://github.com/CyCoreSystems/docker-meteor/), [cluxter/meteor-install](https://hub.docker.com/r/cluxter/meteor-install/), etc. if they choose to support `meteor-up`.  Though currently, I think `abernix/spaceglue` is the only image which maintains the various ways that the `meteorhacks/meteord` worked with `BUNDLE_URL`, `/bundle` mounts, etc.

With this PR, I'll be able to start asking `mup` users to test the new image (it works fine for me with this change).  Without this PR, I'm sure the existing stuff will continue to work fine, but it limits the images which can be used with this to those that continue using `sudo` and port 80 internally, which is not a best-practice any longer.

Let me know if you have any thoughts!

### CODE REVIEW

**Comment by 0o-de-lally** [comment]
@madushan1000 can we add this pull request?

**Comment by aleritty** [comment]
+1

**Comment by madushan1000** [comment]
Can someone check if this PR works with the old mup.js files?

**Comment by abernix** [comment]
I guess I should specify what I tested myself:

* I ran the tests from the [CONTRIBUTING.md](https://github.com/kadirahq/meteor-up/blob/master/CONTRIBUTING.md) and they ran successfully aside from a `mongo` failure which happened with or without this pull
* I ran this against my own Meteor 1.4 project using `docker: { image: 'abernix/meteord:base' }` (old image without `imagePort`) and it worked successfully
* I ran this against my own Meteor 1.4 project using `docker: { image: 'abernix/spaceglue:node-4-builddeps' }` (without `imagePort`) and it failed (as **expected**, since `spaceglue` is on port 3000) 
* I ran this against my own Meteor 1.4 project using `docker: { image: 'abernix/spaceglue:node-4-builddeps', imagePort: 3000 }` (with `imagePort`) and it worked successfully
* This [forum post](https://forums.meteor.com/t/docker-team-up-to-create-a-reference-docker-image-for-meteor/30829/49?u=abernix) indicates that it works as well.

I'd love if others could test too!

**Comment by 0o-de-lally** [comment]
@madushan1000  are the old mup.js files the ones in your test suite?

**Comment by marcoschwartz** [comment]
@madushan1000 Would be great indeed if this could be merged soon, it would be great to be able to use an up-to-date Docker image for Meteor projects :)

**Comment by giordanocardillo** [comment]
Duplicate #299

**Comment by abernix** [comment]
@giordanocardillo That is not a duplicate; Your PR provides entirely different functionality.  This PR is to change the internal port that the Docker image has exposed, not the published port.

**Comment by joadr** [comment]
any news on this?

**Comment by zodern** [comment]
@abernix thanks for making these changes. Would you be able to fix the merge conflicts?

**Comment by abernix** [comment]
@zodern Conflicts resolved!  Sorry I didn't notice this request earlier!

(Note: I only did the conflicts in the GitHub GUI and did not test again, so you might want to look carefully!) :wink:

**Comment by zodern** [comment]
@abernix Thanks. I will merge it later today.

I am thinking of changing the default port to 3000 by setting the `PORT` env variable on the app's container. I looked through the meteord images and the images listed [here](https://docs.google.com/spreadsheets/d/103aHDo8-rFUZ5SvH_HpKQ0GtJGXXkjkLb2MHfmBvHG0/edit#gid=0), and they all support overriding the image's default meteor port with the `PORT` env variable.

**Pull request merged**
