### PR TITLE
mup hooks

### PR DESCRIPTION
**Pull request by JoeyAndres**
Alllow developer to execute shell hooks during various deployment tasks.

### CODE REVIEW

**Comment by JoeyAndres** [comment]
Btw, this can be a draft. Tell me what to change to make this "acceptable".

**Comment by madushan1000** [comment]
HI, Can you add some tests to verify the functionality? take a look at `lib/**/tests/*.js` to get an idea.

**Comment by JoeyAndres** [comment]
@madushan1000 Ok. I'll definitely do that.

**Comment by JoeyAndres** [comment]
Tests are now added.

**Comment by thani-sh** [comment]
How about adding an `exec` function to each module and not exporting functions.

``` js
export function exec(api, fn) {
  // if there are any pre-hooks for `fn` run them
  // run the function `fn`
  // if there are any post-hooks for `fn` run them
}

function deploy(api) {
  // ...
}
```

**Comment by madushan1000** [comment]
Hi @JoeyAndres can you add it as a new test? Without changing any existing tests? Create a new test project directory if you need under `tests/project-<x>`. 
Add a test to check if the scripts run correctly too.

**Comment by JoeyAndres** [comment]
@madushan1000 No problem. Do you want me to do @mnmtanish 's suggestion? I have thought of that, create a class that would aggregate nodemiral so that executeScript/execute can take before/after hooks.

**Comment by JoeyAndres** [comment]
@madushan1000 After reading nodemiral, I can't find a clean way of doing this. Overriding execute/executeScript means overriding [TaskList.registerTask](https://github.com/arunoda/nodemiral/blob/master/lib/taskList.js#L191). I'll just push those separated test.

**Comment by madushan1000** [comment]
@JoeyAndres Great, The test wouldn't change If we change anything in the future anyway. 
@mnmtanish was suggesting that we can use a single `exec` entry point to at each module instead of exporting each deploy related function as we do now. 
This would enable us to run hooks without bolting the specified function. No need to override nodemiaral internals. This would require some design changes.
We think using async functions here would be much cleaner instead of returning promises (which is what we are doing now).
If you think you got the idea, You can take a stab at it. Otherwise, I'll make the changes and ping you when the core is ready to accept hooks PR so you can format the code accordingly.

**Comment by JoeyAndres** [comment]
@madushan1000 I'll take a stab at that problem, I think my brain is cooking some idea, wrap each transaction in class, something along those lines.

Edit: I'll just keep the test for this PR, like said above.

**Comment by thani-sh** [comment]
@JoeyAndres @madushan1000  Yes, that'll be a different PR. I'll comment here as soon as it's ready.

**Comment by JoeyAndres** [comment]
@madushan1000 This PR is now only tests.

**Comment by madushan1000** [comment]
@JoeyAndres es7 work is now done. You can start working on this.

**Comment by JoeyAndres** [comment]
ok

**Comment by JoeyAndres** [comment]
Before I go on: I have the following prototype of what I want to do:

My plan begins with creating a `MupTask` class:

``` javascript
class MupTask {
  constructor(taskName, fn) {
    this.taskName = taskName;  // I assume that names are like "meteor setup", thus we can easily conver this to a hook name (spine case): "meteor-setup". A cleaner way can easily be made.
    this.fn = fn;

    this._beforeExecFns = [];
    this._afterExecFns = [];

    this.taskList = nodemiral.taskList(this.taskName);
    this.baseHookName = this.taskName.toLowerCase().split(' ').join('-');
  }

  execute(mupApi) {
    this._beforeHook(mupApi);
    this._beforeExecFns.forEach(fn => fn.call(this, mupApi));
    this.fn.call(this, mupApi);
    this._afterHook(mupApi);
    this._afterExecFns.forEach(fn => fn.call(this, mupApi));
  }

  onBeforeExec(hookFn) { this._beforeExecFns.push(hookFn); }

  offBeforeExec(hookFn) {
    let index = this._beforeExecFns.indexOf(hookFn);
    if (index !== -1) { this._beforeExecFns.splice(index, 1); }
  }

  onAfterExec(hookFn) { this._afterExecFns.push(hookFn); }

  offAfterExec(hookFn) {
    let index = this._afterExecFns.indexOf(hookFn);
    if (index !== -1) { this._afterExecFns.splice(index, 1); }
  }

  // Private.
  _beforeHook(mupApi) {
    let hooksConfig = mupApi.getConfig().hooks;
    let beforeHookName = `before-${this.baseHookName}`;
    if (hooksConfig) { hook(this.taskList, hooksConfig[beforeHookName], `Executing ${beforeHookName}.`); }
  }

  _afterHook(mupApi) {
    let hooksConfig = mupApi.getConfig().hooks;
    let afterHookName = `after-${this.baseHookName}`;
    if (hooksConfig) { hook(this.taskList, hooksConfig[afterHookName], `Executing ${afterHookName}.`); }
  }
}
```

Then an instance of whatever class is created via: One can imagine doing an `export task` in index.js of a module.

``` javascript
let task = new MupTask('meteor setup', function(mupApi) {
  log('exec => mup meteor setup');
  const config = mupApi.getConfig();
  const meteorConfig = config.meteor;
  if (!meteorConfig) {
    console.error('error: no configs found for meteor');
    process.exit(1);
  }

  this.taskList.executeScript('Setup Environment', {
    script: path.resolve(__dirname, 'assets/meteor-setup.sh'),
    vars: {
      name: meteorConfig.name
    }
  });

  if (meteorConfig.ssl) {
    this.taskList.copy('Copying SSL Certificate Bundle', {
      src: meteorConfig.ssl.crt,
      dest: '/opt/' + meteorConfig.name + '/config/bundle.crt'
    });

    this.taskList.copy('Copying SSL Private Key', {
      src: meteorConfig.ssl.key,
      dest: '/opt/' + meteorConfig.name + '/config/private.key'
    });

    this.taskList.executeScript('Verifying SSL Configurations', {
      script: path.resolve(__dirname, 'assets/verify-ssl-config.sh'),
      vars: {
        name: meteorConfig.name
      },
    });
  }

  const sessions = mupApi.getSessions([ 'meteor' ]);

  return runTaskList(this.taskList, sessions);
});
```

In the lib/execute.js, do:

``` javascript
// command = 'task'
module[command](api);
```

I think MupTask was general enough. Are you guys fine with this solution. I think this will give us a good consistency, plus, other developers won't have to think about hooks anymore.

**Comment by Ben305** [comment]
I like the MupTask class and would use it to install additional packages via apt

**Comment by JoeyAndres** [comment]
This got lost in my work. I got swamped in the last few months. I'll work on this, this long weekend.

**Comment by shadowcodex** [comment]
@zodern @JoeyAndres is this still a direction we want to go with mup?

**Comment by zodern** [comment]
Yes it is.

@JoeyAndres would you be able to finish this?

**Comment by zodern** [comment]
Hooks are available in the `dev` branch.

**Pull request closed without merging**
