### PR TITLE
Fix deployment check for multiple networks on host

### PR DESCRIPTION
**Pull request by eluck**
Docker inspect outputs multiple IP addresses on the same line. It makes the deployment check fail.

Solution:
1. Output IP addresses one per line
2. Pick the first one

### CODE REVIEW

**Comment by zodern** [comment]
Thanks @eluck. Could you please fix the merge conflicts?

**Comment by eluck** [comment]
@zodern Sure

**Comment by eluck** [comment]
@zodern Merge conflicts are resolved. Ready for review and merge

**Comment by zodern** [comment]
Thanks @eluck

**Comment by ilan-schemoul** [comment]
why it is not merged into the master branch and then released into a update.
This is a 5 lines hotfix of a very important problem shouldnt it have been merged into master and be into a new minor release ASAP ?

**Comment by ilan-schemoul** [comment]
Very unfortunately with eluck having destroyed his branch before release and with me obviously not wanting to use the dev branch I'd have to clone this repo cherry pick the commit from this PR and find a way to reinstall the mup package from there ?
Please @zodern cherry pick and make a release.

**Pull request merged**
